import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Search App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			className="transition-colors bg-neutral-100 dark:bg-neutral-800"
			lang="en"
			suppressHydrationWarning={true}
		>
			<body className={inter.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
